language: java

install:
  # Download dependencies with JDK 8 because Mave Central supports
  # TLS 1.2 only but OpenJDK 6 does not.
  - export ORIGINAL_JAVA_HOME=$JAVA_HOME
  - jdk_switcher use oraclejdk8
  - mvn test -DskipTests
  # Delete all files created with JDK 8
  - mvn clean
  # Restore desired JDK
  - export JAVA_HOME=$ORIGINAL_JAVA_HOME
  # Run original install command but without GPG signing
  - mvn install -DskipTests

jdk:
  - openjdk6
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10

before_install: umask 0022
script: mvn install -DskipTests=true
