language: java
sudo: yes
sudo_user: root
file: src=/home/jenkins dest=/home/hudson state=link owner=jenkins group=jenkins
jdk: openjdk6
script: mvn clean $MAIN_ARGS
after_success: $COVERALLS_ARGS
branches:
	only:
		- master
name: setup user | set umask in .profile
sudo: yes
sudo_user: root
lineinfile: dest=/home/jenkins/.profile
line="umask 022"
state=present
