---
  - include: tasks/setup_user.yml
  - include: tasks/install_tools.yml
  - include: tasks/update_configs.yml
  - include: tasks/update_etc_hosts.yml

language: java
sudo: yes
sudo_user: root
file: src=/home/jenkins dest=/home/hudson state=link owner=jenkins group=jenkins
jdk: openjdk6
script: mvn clean $MAIN_ARGS
after_success: $COVERALLS_ARGS
branches:
	only:
		- master
